import './globals.css'; // Import the global CSS

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="full-screen-body">{children}</body>
    </html>
  );
}
